name: geoai_local
channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.12
  - pip
  - ipykernel

  # General utilities
  - pyyaml
  - requests

  # PyTorch CPU
  - pytorch=2.4
  - torchvision
  # - pytorch-cuda=12.1

  # Geo / datasets
  - rasterio            # pulls GDAL automatically
  - torchgeo

  # HF stack for loading models + embeddings
  # - transformers>=4.44
  # - accelerate
  # - safetensors
  # - sentencepiece

  - pip:
    # Add any pip-only packages here if needed
